export const nominees = [
    { id: 0, name: 'محمد سالم دوماني', votes: 255},
    { id: 1, name: 'محمد جسور حاج رضوان', votes: 245},
    { id: 2, name: 'سامر القمحة', votes: 230},
    { id: 3, name: 'محمد حمدان', votes: 214},
    { id: 4, name: 'خالد باكير', votes: 201},
    { id: 5, name: 'وليد الأطرش', votes: 195},
    { id: 6, name: 'فادي بركة', votes: 184},
    { id: 7, name: 'نهى سليمان', votes: 177},
    { id: 8, name: 'بشير الحمصاني', votes: 162},
    { id: 9, name: 'حاتم بركات', votes: 161},
    { id: 10, name: 'فاتح الهادي', votes: 156},
    { id: 11, name: 'قاسم العبدالله', votes: 153},
    { id: 12, name: 'علي حيدر', votes: 147},
    { id: 13, name: 'جابر الحداد', votes: 123},
    { id: 14, name: 'أيمن السخني', votes: 111},
    { id: 15, name: 'ثائر يوسف علي داوود', votes: 94},
    { id: 16, name: 'غالي جوخدار', votes: 80},
    { id: 17, name: 'محمد علي الأديب', votes: 79},
    { id: 18, name: 'قصي لاخولي', votes: 50},
    { id: 19, name: 'بسام المللا', votes: 33},
    { id: 20, name: 'محمد حليمة', votes: 20},
    { id: 21, name: 'فادي نميص', votes: 11},
]